import { Inter} from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import  Header from "@/components/Header"
import "./globals.css";
import { dark, shadesOfPurple } from '@clerk/themes';
import { auth } from "@clerk/nextjs/server"; 

import {
ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Toaster } from "sonner";
const inter =Inter({ subsets: ["latin"]});
export const metadata = {
  title: "Sensi AI CAREER COACH ",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>
            <footer className="bg-muted/50 py-12 ">
              <div className="container  mx-auto px-4 text-center  text-gray-200">
                <p>Made by Saatwik</p>
              </div>
            </footer>
            
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
